USE sisat;

UPDATE evaluacion_sisat
SET NIVEL_RIESGO = CASE
    WHEN PUNTAJE_RIESGO <= 2 THEN 'BAJO'
    WHEN PUNTAJE_RIESGO <= 5 THEN 'MEDIO'
    WHEN PUNTAJE_RIESGO <= 8 THEN 'ALTO'
    ELSE 'CRITICO'
END
WHERE NIVEL_RIESGO = '' OR NIVEL_RIESGO IS NULL;

SELECT NIVEL_RIESGO, COUNT(*) total
FROM evaluacion_sisat
GROUP BY NIVEL_RIESGO;